[tool.poetry]
name = "fgo-game-data-api"
version = "5.78.0"
description = "Provide raw and processed FGO game data"
authors = ["squaresmile <squaresmile@protonmail.com>"]
packages = [{ include = "app" }]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.85.1"
uvicorn = { extras = ["standard"], version = "^0.19.0" }
python-dotenv = "^0.21.0"
fuzzywuzzy = { extras = ["speedup"], version = "^0.18.0" }
orjson = "^3.8.1"
aiofiles = "^22.1.0"
GitPython = "^3.1.29"
SQLAlchemy = "^1.4.42"
psycopg2 = "^2.9.5"
httpx = "^0.23.0"
asyncpg = "^0.27.0"
fastapi-cache2 = "^0.1.9"
gunicorn = "^20.1.0"
setproctitle = "^1.3.2"
redis = "^4.3.4"
hiredis = "^2.0.0"

[tool.poetry.group.dev.dependencies]
mypy = "^0.982"
pylint = "^2.15.5"
black = "^22.10.0"
isort = "^5.10.1"
pytest = "^7.2.0"
pytest-xdist = "^3.0.2"
pytest-asyncio = "^0.20.1"
coverage = "^6.5.0"
asgi-lifespan = "^1.0.1"
fuzzywuzzy-stubs = "^0.0.1"
sqlalchemy2-stubs = "^0.0.2a29"
types-aiofiles = "^22.1.0"
types-redis = "^4.3.21.3"
types-orjson = "^3.6.2"

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.isort]
line_length = 88
profile = "black"
known_third_party = "orjson"
lines_after_imports = 2
extra_standard_library = ["tomllib"]

[tool.black]
target-version = ['py310']

[tool.mypy]
plugins = "pydantic.mypy, sqlalchemy.ext.mypy.plugin"

follow_imports = "normal"
show_column_numbers = true

# mypy strict options
warn_unused_configs = true
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_reexport = true
strict_equality = true

[[tool.mypy.overrides]]
module = ["fastapi_cache.*"]
no_implicit_reexport = false
ignore_missing_imports = true

[tool.pylint.MASTER]
extension-pkg-whitelist = "orjson,pydantic"

[tool.pylint.'MESSAGES CONTROL']
disable = "duplicate-code,invalid-name,line-too-long,logging-fstring-interpolation,missing-docstring,no-else-return,raise-missing-from,too-few-public-methods,too-many-arguments,too-many-branches,too-many-instance-attributes,too-many-lines,too-many-locals,too-many-nested-blocks,too-many-statements,wrong-import-order,unhashable-member"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
